name = "sweet-forest-c602"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改
id = "7d0f10e344944dc0b8956e0511e4703f"				#KV数据库id
